# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1stZriG8guhuMQIfPZlFVXaqPv2214SOA
"""

import streamlit as st
import pandas as pd
import pickle
import numpy as np

# Muat model dan encoder yang telah diupload
model_file = st.file_uploader("Upload Model", type=["pkl"])
encoder_file = st.file_uploader("Upload Label Encoder", type=["pkl"])

if model_file is not None and encoder_file is not None:
    with open(model_file, 'rb') as f:
        model = pickle.load(f)

    with open(encoder_file, 'rb') as f:
        label_encoders = pickle.load(f)

    st.write("Model dan Label Encoder berhasil dimuat!")
else:
    st.write("Harap upload file model dan label encoder.")

# Input form untuk data prediksi
input_data = {
    'Booking_ID': 'INN00002',  # Ganti dengan Booking ID yang relevan
    'no_of_adults': 2,
    'no_of_children': 1,
    'no_of_weekend_nights': 2,
    'no_of_week_nights': 3,
    'type_of_meal_plan_Meal Plan 2': 1,
    'type_of_meal_plan_Meal Plan 3': 0,
    'type_of_meal_plan_Not Selected': 0,
    'room_type_reserved_Room_Type 2': 0,
    'room_type_reserved_Room_Type 3': 0,
    'room_type_reserved_Room_Type 4': 1,
    'room_type_reserved_Room_Type 5': 0,
    'room_type_reserved_Room_Type 6': 0,
    'room_type_reserved_Room_Type 7': 0,
    'lead_time': 35,
    'arrival_year': 2018,
    'arrival_month': 5,
    'arrival_date': 12,
    'market_segment_type_Corporate': 0,
    'market_segment_type_Offline': 0,
    'market_segment_type_Online': 1,
    'market_segment_type_Complementary': 0,
    'repeated_guest': 0,
    'no_of_previous_cancellations': 0,
    'no_of_previous_bookings_not_canceled': 0,
    'avg_price_per_room': 105.5,
    'no_of_special_requests': 1,
}

# Menambahkan kolom yang hilang (0 untuk fitur yang tidak diisi)
input_data['room_type_reserved_Room_Type 1'] = 0
input_data['type_of_meal_plan_Meal Plan 1'] = 0
input_data['market_segment_type_Aviation'] = 0

# Proses prediksi jika file model dan encoder sudah dimuat
if model_file and encoder_file:
    # Membuat DataFrame dari input
    df_input = pd.DataFrame(input_data, index=[0])

    # Menyusun urutan kolom sesuai dengan fitur model
    feature_order = ['no_of_adults', 'no_of_children', 'no_of_weekend_nights', 'no_of_week_nights', 'lead_time',
                     'arrival_year', 'arrival_month', 'arrival_date', 'repeated_guest', 'no_of_previous_cancellations',
                     'no_of_previous_bookings_not_canceled', 'avg_price_per_room', 'no_of_special_requests',
                     'type_of_meal_plan_Meal Plan 1', 'type_of_meal_plan_Meal Plan 2', 'type_of_meal_plan_Meal Plan 3',
                     'type_of_meal_plan_Not Selected', 'room_type_reserved_Room_Type 1', 'room_type_reserved_Room_Type 2',
                     'room_type_reserved_Room_Type 3', 'room_type_reserved_Room_Type 4', 'room_type_reserved_Room_Type 5',
                     'room_type_reserved_Room_Type 6', 'room_type_reserved_Room_Type 7', 'market_segment_type_Aviation',
                     'market_segment_type_Complementary', 'market_segment_type_Corporate', 'market_segment_type_Offline',
                     'market_segment_type_Online']

    df_input = df_input[feature_order]

    # Menampilkan data yang diproses untuk prediksi
    st.write("Data yang telah diproses untuk prediksi:")
    st.write(df_input)

    # Lakukan prediksi
    prediction = model.predict(df_input)[0]
    probability = model.predict_proba(df_input)[:, 1]  # Probability untuk kelas "Canceled"

    # Menampilkan hasil prediksi dan probabilitas
    status = "Not Cancelled" if prediction == 0 else "Cancelled"
    st.write(f"Prediction Result: {status}")
    st.write(f"Cancellation Probability: {probability[0]:.2%}")